import pandas as pd

basketball = pd.read_csv("cleaned_data/cleaned_college_basketball.csv")
scorecard = pd.read_csv("cleaned_data/scorecard_cleaned.csv")

basketball_to_scorecard = {
    "abilene christian": "abilene christian university",
    "air force": "united states air force academy",
    "akron": "university of akron main campus",
    "alabama": "the university of alabama",
    "alabama a&m": "alabama a & m university",
    "alabama state": "alabama state university",
    "albany (ny)": "university at albany",
    "alcorn state": "alcorn state university",
    "american": "american university",
    "appalachian state": "appalachian state university",
    "arizona": "university of arizona",
    "arizona state": "arizona state university campus immersion",
    "arkansas": "university of arkansas",
    "arkansas state": "arkansas state university",
    "arkansas-pine bluff": "university of arkansas at pine bluff",
    "army": "united states military academy",
    "auburn": "auburn university",
    "austin peay": "austin peay state university",
    "ball state": "ball state university",
    "baylor": "baylor university",
    "bellarmine": "bellarmine university",
    "belmont": "belmont university",
    "bethune-cookman": "bethune-cookman university",
    "binghamton": "binghamton university",
    "boise state": "boise state university",
    "boston college": "boston college",
    "boston university": "boston university",
    "bowling green": "bowling green state university-main campus",
    "bradley": "bradley university",
    "brigham young": "brigham young university",
    "brown": "brown university",
    "bryant": "bryant university",
    "bucknell": "bucknell university",
    "buffalo": "university at buffalo",
    "butler": "butler university",
    "cal poly": "california polytechnic state university-san luis obispo",
    "cal state bakersfield": "california state university-bakersfield",
    "cal state fullerton": "california state university-fullerton",
    "cal state northridge": "california state university-northridge",
    "california": "university of california-berkeley",
    "california baptist": "california baptist university",
    "campbell": "campbell university",
    "canisius": "canisius university",
    "central arkansas": "university of central arkansas",
    "central connecticut state": "central connecticut state university",
    "central michigan": "central michigan university",
    "charleston southern": "charleston southern university",
    "charlotte": "university of north carolina at charlotte",
    "chattanooga": "the university of tennessee-chattanooga",
    "chicago state": "chicago state university",
    "cincinnati": "university of cincinnati-main campus",
    "clemson": "clemson university",
    "cleveland state": "cleveland state university",
    "coastal carolina": "coastal carolina university",
    "colgate": "colgate university",
    "college of charleston": "college of charleston",
    "colorado": "university of colorado boulder",
    "colorado state": "colorado state university-fort collins",
    "columbia": "columbia university in the city of new york",
    "connecticut": "university of connecticut",
    "coppin state": "coppin state university",
    "cornell": "cornell university",
    "creighton": "creighton university",
    "dartmouth": "dartmouth college",
    "davidson": "davidson college",
    "dayton": "university of dayton",
    "delaware": "university of delaware",
    "delaware state": "delaware state university",
    "denver": "university of denver",
    "depaul": "depaul university",
    "detroit mercy": "university of detroit mercy",
    "drake": "drake university",
    "drexel": "drexel university",
    "duke": "duke university",
    "duquesne": "duquesne university",
    "east carolina": "east carolina university",
    "east tennessee state": "east tennessee state university",
    "east texas a&m": "east texas a&m university",
    "eastern illinois": "eastern illinois university",
    "eastern kentucky": "eastern kentucky university",
    "eastern michigan": "eastern michigan university",
    "eastern washington": "eastern washington university",
    "elon": "elon university",
    "evansville": "university of evansville",
    "fairfield": "fairfield university",
    "fdu": "fairleigh dickinson university-florham campus",
    "florida": "university of florida",
    "florida a&m": "florida agricultural and mechanical university",
    "florida atlantic": "florida atlantic university",
    "florida gulf coast": "florida gulf coast university",
    "florida international": "florida international university",
    "florida state": "florida state university",
    "fordham": "fordham university",
    "fresno state": "california state university-fresno",
    "furman": "furman university",
    "gardner-webb": "gardner-webb university",
    "george mason": "george mason university",
    "george washington": "george washington university",
    "georgetown": "georgetown university",
    "georgia": "university of georgia",
    "georgia southern": "georgia southern university",
    "georgia state": "georgia state university",
    "georgia tech": "georgia institute of technology-main campus",
    "gonzaga": "gonzaga university",
    "grambling": "grambling state university",
    "grand canyon": "grand canyon university",
    "green bay": "university of wisconsin-green bay",
    "hampton": "hampton university",
    "hartford": "university of hartford",
    "harvard": "harvard university",
    "hawaii": "university of hawaii at manoa",
    "high point": "high point university",
    "hofstra": "hofstra university",
    "holy cross": "college of the holy cross",
    "houston": "university of houston",
    "houston christian": "houston christian university",
    "howard": "howard university",
    "idaho": "university of idaho",
    "idaho state": "idaho state university",
    "illinois": "university of illinois urbana-champaign",
    "illinois state": "illinois state university",
    "illinois-chicago": "university of illinois chicago",
    "incarnate word": "university of the incarnate word",
    "indiana": "indiana university-bloomington",
    "indiana state": "indiana state university",
    "iona": "iona university",
    "iowa": "university of iowa",
    "iowa state": "iowa state university",
    "iu indy": "indiana university-indianapolis", 
    "jackson state": "jackson state university",
    "jacksonville": "jacksonville university",
    "jacksonville state": "jacksonville state university",
    "james madison": "james madison university",
    "kansas": "university of kansas",
    "kansas city": "university of missouri-kansas city",
    "kansas state": "kansas state university",
    "kennesaw state": "kennesaw state university",
    "kent state": "kent state university at kent",
    "kentucky": "university of kentucky",
    "la salle": "la salle university",
    "lafayette": "lafayette college",
    "lamar": "lamar university",
    "le moyne": "le moyne college",
    "lehigh": "lehigh university",
    "liberty": "liberty university",
    "lindenwood": "lindenwood university",
    "lipscomb": "lipscomb university",
    "little rock": "university of arkansas at little rock",
    "long beach state": "california state university-long beach",
    "long island university": "long island university",
    "longwood": "longwood university",
    "louisiana": "university of louisiana at lafayette",
    "louisiana state": "louisiana state university and agricultural & mechanical college",
    "louisiana tech": "louisiana tech university",
    "louisiana-monroe": "university of louisiana at monroe",
    "louisville": "university of louisville",
    "loyola (il)": "loyola university chicago",
    "loyola (md)": "loyola university maryland",
    "loyola marymount": "loyola marymount university",
    "maine": "university of maine",
    "manhattan": "manhattan university",
    "marist": "marist university",
    "marquette": "marquette university",
    "marshall": "marshall university",
    "maryland": "university of maryland-college park",
    "maryland-baltimore county": "university of maryland-baltimore county",
    "maryland-eastern shore": "university of maryland eastern shore",
    "massachusetts": "university of massachusetts-amherst",
    "massachusetts-lowell": "university of massachusetts-lowell",
    "mcneese": "mcneese state university",
    "memphis": "university of memphis",
    "mercer": "mercer university",
    "merrimack": "merrimack college",
    "miami (fl)": "university of miami",
    "miami (oh)": "miami university-oxford",
    "michigan": "university of michigan-ann arbor",
    "michigan state": "michigan state university",
    "middle tennessee": "middle tennessee state university",
    "milwaukee": "university of wisconsin-milwaukee",
    "minnesota": "university of minnesota-twin cities",
    "mississippi": "university of mississippi",
    "mississippi state": "mississippi state university",
    "mississippi valley state": "mississippi valley state university",
    "missouri": "university of missouri-columbia",
    "missouri state": "missouri state university-springfield",
    "monmouth": "monmouth university",
    "montana": "the university of montana",
    "montana state": "montana state university",
    "morehead state": "morehead state university",
    "morgan state": "morgan state university",
    "mount st. mary's": "mount st. mary's university",
    "murray state": "murray state university",
    "navy": "united states naval academy",
    "nc state": "north carolina state university at raleigh",
    "nebraska": "university of nebraska-lincoln",
    "nevada": "university of nevada-reno",
    "nevada-las vegas": "university of nevada-las vegas",
    "new hampshire": "university of new hampshire-main campus",
    "new mexico": "university of new mexico-main campus",
    "new mexico state": "new mexico state university-main campus",
    "new orleans": "university of new orleans",
    "niagara": "niagara university",
    "nicholls state": "nicholls state university",
    "njit": "new jersey institute of technology",
    "norfolk state": "norfolk state university",
    "north alabama": "university of north alabama",
    "north carolina": "university of north carolina at chapel hill",
    "north carolina a&t": "north carolina a & t state university",
    "north carolina central": "north carolina central university",
    "north dakota": "university of north dakota",
    "north dakota state": "north dakota state university-main campus",
    "north florida": "university of north florida",
    "north texas": "university of north texas",
    "northeastern": "northeastern university",
    "northern arizona": "northern arizona university",
    "northern colorado": "university of northern colorado",
    "northern illinois": "northern illinois university",
    "northern iowa": "university of northern iowa",
    "northern kentucky": "northern kentucky university",
    "northwestern": "northwestern university",
    "northwestern state": "northwestern state university of louisiana",
    "notre dame": "university of notre dame",
    "oakland": "oakland university",
    "ohio": "ohio university-main campus",
    "ohio state": "ohio state university-main campus",
    "oklahoma": "university of oklahoma-norman campus",
    "oklahoma state": "oklahoma state university-main campus",
    "old dominion": "old dominion university",
    "omaha": "university of nebraska at omaha",
    "oral roberts": "oral roberts university",
    "oregon": "university of oregon",
    "oregon state": "oregon state university",
    "pacific": "university of the pacific",
    "penn state": "pennsylvania state university-main campus",
    "pennsylvania": "university of pennsylvania",
    "pepperdine": "pepperdine university",
    "pittsburgh": "university of pittsburgh-pittsburgh campus",
    "portland": "university of portland",
    "portland state": "portland state university",
    "prairie view a&m": "prairie view a & m university",
    "presbyterian": "presbyterian college",
    "princeton": "princeton university",
    "providence": "providence college",
    "purdue": "purdue university-main campus",
    "purdue fort wayne": "purdue university fort wayne",
    "queens (nc)": "queens university of charlotte",
    "quinnipiac": "quinnipiac university",
    "radford": "radford university",
    "rhode island": "university of rhode island",
    "rice": "rice university",
    "richmond": "university of richmond",
    "rider": "rider university",
    "robert morris": "robert morris university",
    "rutgers": "rutgers university-new brunswick",
    "sacramento state": "california state university-sacramento",
    "sacred heart": "sacred heart university",
    "saint francis (pa)": "saint francis university",
    "saint joseph's": "saint joseph's university - philadelphia",
    "saint louis": "saint louis university",
    "saint mary's": "saint mary's college of california",
    "saint peter's": "saint peter's university",
    "sam houston": "sam houston state university",
    "samford": "samford university",
    "san diego": "university of san diego",
    "san diego state": "san diego state university",
    "san francisco": "university of san francisco",
    "san jose state": "san jose state university",
    "santa clara": "santa clara university",
    "savannah state": "savannah state university",
    "seattle": "seattle university",
    "seton hall": "seton hall university",
    "siena": "siena college",
    "siu edwardsville": "southern illinois university edwardsville",
    "south alabama": "university of south alabama",
    "south carolina": "university of south carolina-columbia",
    "south carolina state": "south carolina state university",
    "south carolina upstate": "university of south carolina-upstate",
    "south dakota": "university of south dakota",
    "south dakota state": "south dakota state university",
    "south florida": "university of south florida",
    "southeast missouri state": "southeast missouri state university",
    "southeastern louisiana": "southeastern louisiana university",
    "southern": "southern university and a & m college",
    "southern california": "university of southern california",
    "southern illinois": "southern illinois university-carbondale",
    "southern indiana": "university of southern indiana",
    "southern methodist": "southern methodist university",
    "southern mississippi": "university of southern mississippi",
    "southern utah": "southern utah university",
    "st. bonaventure": "st bonaventure university",
    "st. francis (ny)": "st. francis college",
    "st. john's (ny)": "st. john's university-new york",
    "st. thomas": "university of st thomas",
    "stanford": "stanford university",
    "stephen f. austin": "stephen f austin state university",
    "stetson": "stetson university",
    "stonehill": "stonehill college",
    "stony brook": "stony brook university",
    "syracuse": "syracuse university",
    "tarleton state": "tarleton state university",
    "temple": "temple university",
    "tennessee": "the university of tennessee-knoxville",
    "tennessee state": "tennessee state university",
    "tennessee tech": "tennessee technological university",
    "tennessee-martin": "the university of tennessee-martin",
    "texas": "the university of texas at austin",
    "texas a&m": "texas a&m university-college station",
    "texas a&m-corpus christi": "texas a & m university-corpus christi",
    "texas christian": "texas christian university",
    "texas southern": "texas southern university",
    "texas state": "texas state university",
    "texas tech": "texas tech university",
    "texas-rio grande valley": "the university of texas rio grande valley",
    "the citadel": "citadel military college of south carolina",
    "toledo": "university of toledo",
    "towson": "towson university",
    "troy": "troy university",
    "tulane": "tulane university of louisiana",
    "tulsa": "university of tulsa",
    "uab": "university of alabama at birmingham",
    "uc davis": "university of california-davis",
    "uc irvine": "university of california-irvine",
    "uc riverside": "university of california-riverside",
    "uc san diego": "university of california-san diego",
    "uc santa barbara": "university of california-santa barbara",
    "ucf": "university of central florida",
    "ucla": "university of california-los angeles",
    "unc asheville": "university of north carolina asheville",
    "unc greensboro": "university of north carolina at greensboro",
    "unc wilmington": "university of north carolina wilmington",
    "ut arlington": "the university of texas at arlington",
    "utah": "university of utah",
    "utah state": "utah state university",
    "utah tech": "utah tech university",
    "utah valley": "utah valley university",
    "utep": "the university of texas at el paso",
    "utsa": "the university of texas at san antonio",
    "valparaiso": "valparaiso university",
    "vanderbilt": "vanderbilt university",
    "vermont": "university of vermont",
    "villanova": "villanova university",
    "virginia": "university of virginia-main campus",
    "virginia commonwealth": "virginia commonwealth university",
    "virginia tech": "virginia polytechnic institute and state university",
    "vmi": "virginia military institute",
    "wagner": "wagner college",
    "wake forest": "wake forest university",
    "washington": "university of washington-seattle campus",
    "washington state": "washington state university",
    "weber state": "weber state university",
    "west virginia": "west virginia university",
    "western carolina": "western carolina university",
    "western illinois": "western illinois university",
    "western kentucky": "western kentucky university",
    "western michigan": "western michigan university",
    "wichita state": "wichita state university",
    "william & mary": "william & mary",
    "winthrop": "winthrop university",
    "wisconsin": "university of wisconsin-madison",
    "wofford": "wofford college",
    "wright state": "wright state university-main campus",
    "wyoming": "university of wyoming",
    "xavier": "xavier university",
    "yale": "yale university",
    "youngstown state": "youngstown state university",
}

def get_scorecard_name(basketball_school: str):
    key = basketball_school.lower().replace("\xa0ncaa", "").strip()
    return basketball_to_scorecard.get(key)

basketball["clean_name"] = basketball["School"].apply(get_scorecard_name)

merged_df = pd.merge(scorecard, basketball, how = "inner", left_on = ["institution_name", "year"], right_on = ["clean_name", "Year"])

merged_df.to_csv("cleaned_data/integrated_data.csv", index = False)